"""[test] Drop date in Opeatrtion

Revision ID: 332fa334e5d8
Revises: 560165aac048
Create Date: 2022-11-06 14:10:39.133933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332fa334e5d8'
down_revision = '560165aac048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
